import { View, Text } from "react-native";
import React from "react";
import { Icon } from "react-native-gradient-icon";

export default function Ratings({ratings}) {
    
  return (
    <View>
      {ratings === 1&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
        </View>
      }
      {ratings === 1.5&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star-half" 
                    type="ionicon" 
                />
        </View>
      }{ratings === 2&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
        </View>
      }
      {ratings === 2.5&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star-half" 
                    type="ionicon" 
                />
        </View>
      }{ratings === 3&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
             <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
        </View>
      }
      {ratings === 3.5&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
             <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
               <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star-half" 
                    type="ionicon" 
                />
        </View>
      }
      {ratings === 4&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
             <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
               
        </View>
      }
      {ratings === 4.5&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
             <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
                <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
               <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star-half" 
                    type="ionicon" 
                />
        </View>
      }
      {ratings === 5&&
        <View style={{flexDirection: 'row',}}>
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
            <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
             <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
                <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
               <Icon  
                    size={12}
                    colors={[
                        {color:"#B615DE",offset:"0",opacity:"1"},
                        {color:"#D428A8",offset:"1",opacity:"1"},
                    ]}
                    name="md-star" 
                    type="ionicon" 
                />
        </View>
      }
    </View>
  );
}
